// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DimensionsLoadConsole.Entities.Northwind

{
    [Table("VWClientEmployee")]
    public class VwclientEmployee
    {
        public string? ClienteAtendidoKey { get; set; }

        public int EmployeeKey { get; set; }

        public int TotalClientes { get; set; }
    }
}