// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DimensionsLoadConsole.Entities.DWHNorthwindOrders
{
    [Table("DimEmployees")]
    public partial class DimEmployee
    {
        [Key]
        public int EmployeeKey { get; set; }

        public string? EmployeeName { get; set; }

        public int EmployeeId { get; set; }

    }
}