// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DimensionsLoadConsole.Entities.DWHNorthwindOrders
{

    [Table("DimShippers")]
    public class DimShipper
    {


        [Key]
        public int ShipperKey { get; set; }
        public int ShipperId { get; set; }
        public string? ShipperName { get; set; }
    }
}