// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace DimensionsLoadConsole.Entities.DWHNorthwindOrders
{
    [Table("FactClientesAtendidos")]

    public partial class FactClientesAtendido
    {
        [Key]
        public string? ClienteAtendidoKey { get; set; }

        public int EmployeeKey { get; set; }

        public int TotalClientes { get; set; }


    }
}